### ISSUE TITLE
Cant build CMake in Julia 1.1?

### ISSUE THREAD

**Issue by AlexanderSugar** [JuliaPackaging/CMake.jl#14] opened 2019-05-03 02:02 UTC
Any help would be appreciated, I get the following error, I have no idea how to proceed.

This is on a clean julia install, installed via https://github.com/abelsiqueira/jill, all I did was run update and then try to install a package that has CMake as a dependency.

```
julia> Pkg.build("CMake")
  Building CMake → `~/.julia/packages/CMake/ZGawK/deps/build.log`
┌ Error: Error building `CMake`: 
│ [ Info: Attempting to create directory /home/alex/.julia/packages/CMake/ZGawK/deps/downloads
│ [ Info: Directory /home/alex/.julia/packages/CMake/ZGawK/deps/downloads already exists
│ [ Info: Downloading file https://github.com/Kitware/CMake/releases/download/v3.12.3/cmake-3.12.3-Linux-x86_64.tar.gz
│ [ Info: Done downloading file https://github.com/Kitware/CMake/releases/download/v3.12.3/cmake-3.12.3-Linux-x86_64.tar.gz
│ [ Info: Attempting to create directory /home/alex/.julia/packages/CMake/ZGawK/deps
│ [ Info: Directory /home/alex/.julia/packages/CMake/ZGawK/deps already exists
│ [ Info: Path /home/alex/.julia/packages/CMake/ZGawK/deps/downloads/cmake-3.12.3-Linux-x86_64 already exists
│ [ Info: Attempting to create directory /home/alex/.julia/packages/CMake/ZGawK/deps/usr/bin
│ [ Info: Directory /home/alex/.julia/packages/CMake/ZGawK/deps/usr/bin already exists
│ ERROR: LoadError: SystemError: unable to read directory /home/alex/.julia/packages/CMake/ZGawK/deps/downloads/cmake-3.12.3-Linux-x86_64/bin: No such file or directory
│ Stacktrace:
│  [1] readdir(::String) at ./file.jl:625
│  [2] (::getfield(Main, Symbol("##3#4")){String,Bool})() at /home/alex/.julia/packages/CMake/ZGawK/deps/build.jl:55
│  [3] run(::getfield(Main, Symbol("##3#4")){String,Bool}) at /home/alex/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:478
│  [4] run(::BinDeps.SynchronousStepCollection) at /home/alex/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521
│  [5] run(::FileRule) at /home/alex/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:483
│  [6] run(::BinDeps.SynchronousStepCollection) at /home/alex/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521
│  [7] top-level scope at none:0
│  [8] include at ./boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1038
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at /home/alex/.julia/packages/CMake/ZGawK/deps/build.jl:155
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

```
Thanks in advance!

**Comment by AlexanderSugar** [comment] 2019-05-03 02:16
Of course I figure it out right after posting. What I did was just to create an empty /bin directory where it was looking for one, after which it gives a much more helpful error message:
```
julia> Pkg.build("CMake")
  Building CMake → `~/.julia/packages/CMake/ZGawK/deps/build.log`
┌ Error: Error building `CMake`: 
│ [ Info: Attempting to create directory /home/alex/.julia/packages/CMake/ZGawK/deps/downloads
│ [ Info: Directory /home/alex/.julia/packages/CMake/ZGawK/deps/downloads already exists
│ [ Info: Downloading file https://github.com/Kitware/CMake/releases/download/v3.12.3/cmake-3.12.3-Linux-x86_64.tar.gz
│ [ Info: Done downloading file https://github.com/Kitware/CMake/releases/download/v3.12.3/cmake-3.12.3-Linux-x86_64.tar.gz
│ [ Info: Attempting to create directory /home/alex/.julia/packages/CMake/ZGawK/deps
│ [ Info: Directory /home/alex/.julia/packages/CMake/ZGawK/deps already exists
│ [ Info: Path /home/alex/.julia/packages/CMake/ZGawK/deps/downloads/cmake-3.12.3-Linux-x86_64 already exists
│ [ Info: Attempting to create directory /home/alex/.julia/packages/CMake/ZGawK/deps/usr/bin
│ [ Info: Directory /home/alex/.julia/packages/CMake/ZGawK/deps/usr/bin already exists
│ ERROR: LoadError: Running the precompiled cmake binary failed with the error
│ Base.IOError("could not spawn `/home/alex/.julia/packages/CMake/ZGawK/deps/usr/bin/cmake --version`: no such file or directory (ENOENT)", -2)
│ To build from source instead, run:
│     julia> ENV["CMAKE_JL_BUILD_FROM_SOURCE"] = 1
│     julia> Pkg.build("CMake")

```

Now running the build works.

**Comment by stevengj** [comment] 2019-05-03 02:56
So the precompiled binary is not working for you?  I'm still confused about the root error you are seeing.

**Comment by AlexanderSugar** [comment] 2019-05-03 06:03
When I went to that directory, there was no bin/ directory, just doc and man. I made an empty one and it gave me the new error message. 

So am assuming whatever script is supposed to be compiling it actually wasn't? Or placed it in a different spot from where it was looking. I'm on linux mint btw.

**Comment by haavardhvarnes** [comment] 2019-08-19 19:55
I think I got a similar error on w10:

(v1.1) pkg> build CMake
  Building CMake → `C:\Users\hvarnhav\.julia\packages\CMake\nSK2r\deps\build.log`
┌ Error: Error building `CMake`:
│ ERROR: LoadError: UndefVarError: path not defined
│ Stacktrace:
│  [1] download_cmd(::String, ::String) at C:\Users\hvarnhav\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:87
│  [2] lower(::FileDownloader, ::BinDeps.SynchronousStepCollection) at C:\Users\hvarnhav\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:291
│  [3] macro expansion at C:\Users\hvarnhav\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:291 [inlined]
│  [4] install_binaries(::String, ::String, ::String) at C:\Users\hvarnhav\.julia\packages\CMake\nSK2r\deps\build.jl:81
│  [5] top-level scope at C:\Users\hvarnhav\.julia\packages\CMake\nSK2r\deps\build.jl:139
│  [6] include at .\boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1038
│  [8] include(::Module, ::String) at .\sysimg.jl:29
│  [9] include(::String) at .\client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at C:\Users\hvarnhav\.julia\packages\CMake\nSK2r\deps\build.jl:119

**Comment by stevengj** [comment] 2020-02-12 23:48
CMake#master works for me on Windows 10 with Julia 1.3.1, and CI is passing on Linux, so I'm going to close this as no longer reproducible.

**Closed as completed by stevengj** 2020-02-12 23:48 UTC
